### PR TITLE
Manage CSR view

### PR DESCRIPTION
**Pull request by stevelaskaridis**
## Description

Added approve and reject buttons for each CSR.
## Github issue

The present pull request corresponds to current issue #46.
## Dependencies

PR #41.

### CODE REVIEW

**Comment by stevelaskaridis** [comment]
test this please

**Comment by NicolasLiampotis** [comment]
retest this please

**Comment by stevelaskaridis** [comment]
@NicolasLiampotis: Are you the CI whisperer?

**Comment by NicolasLiampotis** [comment]
@stevelaskaridis: Yes - see #59. I hope to have a fix by tomorrow.

**Pull request merged**
